[theme]
# Dark mode with blue/pink accents
base = "dark"
primaryColor = "#60A5FA"             # Light blue accent
backgroundColor = "#0B1220"          # Very dark navy
secondaryBackgroundColor = "#111827" # Dark gray panels
textColor = "#F9FAFB"                # Near-white text
font = "sans serif"
